### ISSUE TITLE
randAlphaNum transformation destroys column name

### ISSUE THREAD

**Issue by akademic** [nixys/nxs-data-anonymizer#2]
I have source dump sql:

```
DROP TABLE IF EXISTS `groups`;
CREATE TABLE `groups` (
  `id` int NOT NULL,
  `title` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `groups` (`id`, `title`) VALUES
(1, 'Group One'),
(2, 'Group Two');
```

and config

```
filters:
  groups:
    columns:
      title:
        value: "{{- randAlphaNum 50 | nospace | lower -}}"
```

After running `cat ./source.bug.dump.sql| ./nxs-data-anonymizer -t mysql -c config.conf --output ./dest.dump.sql`

I got this output:

```
DROP TABLE IF EXISTS `groups`;
CREATE TABLE `groups` (
  `id` int NOT NULL,
  `title` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3;

INSERT INTO `groups` (`id`,8fwml4vf5igl6vt6lji6igisxuix44ycbon3neegiujvn21yq3) VALUES
(1, 'Group One'),
(2,'bnvv8hlw5b3gmnogsqcw2gaeifareusdkxi8634mhrn9v2fj3f');
```
