### ISSUE TITLE
Security enforcement

### ISSUE THREAD

**Issue by akademic** [nixys/nxs-data-anonymizer#3]
Introduced features are great!

But database structure evolves and you can't just setup filters once and live in peace.

One day someone will add new table with secrets and theese secrets will go to staging without obfuscation.

It will be great to have option to skip all tables not added to config.
Also this option will obfuscate all undescribed columns.

This change will force to update nxs-data-anonymizer config every time we have changed database structure (added column, created table).
This will provide "secure by default" mode.

**Comment by borisershov** [comment]
You mean something like this (example):

```yaml
global:
  columns:
    api:
      value: "{{- randAlphaNum 50 | nospace | lower -}}"
filters:
  groups:
    columns:
      title:
        value: "{{- randAlphaNum 50 | nospace | lower -}}"
``` 

Globally a filters will be applied for column `api` for every table within the database. And for column `title` only for database `groups`.

?

**Comment by akademic** [comment]
Something like:

```
global:
   skip_tables_without_filters: true
   randomize_columns_without_filters: true

filters:
  groups:
    columns:
      id:
        passthrough: true
      api:
        value: "{{- randAlphaNum 50 | nospace | lower -}}"
      // other columns if exist will be randomized with respect to types: int -> random int, string ->random string
```
