### ISSUE TITLE
isNull doesn't work with MySQL dump

### ISSUE THREAD

**Issue by Lavisx** [nixys/nxs-data-anonymizer#54]
I'm used the MySQL dump DB and in filter I use isNull. But ewery result is false.

The simple filters:
```yaml
filters:
  subscriber:
    columns:
      login:
        value: "{{ if isNull .Values.login }}{{ .Values.login }}{{ else }}user_{{ .Values.id }}{{ end }}"
```
